<?php
/**
 * Demo account personas — influence generated history only; do not modify users.
 */
return [
    [
        'id' => 'student_berlin_24',
        'label' => 'John — Student, 24, Berlin',
        'account_style' => 'student',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'city' => 'Berlin',
        'country_hint' => 'Germany',
        'salary_range' => [800, 1400],
        'merchant_tags' => ['coffee', 'streaming', 'tuition', 'transit', 'groceries'],
        'transfer_patterns' => ['small_domestic'],
    ],
    [
        'id' => 'business_owner_dubai',
        'label' => 'Sarah — Business Owner, Dubai',
        'account_style' => 'business',
        'financial_behaviour' => 'active_spender',
        'volume' => 'high',
        'city' => 'Dubai',
        'country_hint' => 'United Arab Emirates',
        'salary_range' => [15000, 45000],
        'merchant_tags' => ['saas', 'supplier', 'payroll', 'tax', 'travel'],
        'transfer_patterns' => ['domestic', 'international'],
    ],
    [
        'id' => 'salaried_uae',
        'label' => 'Ahmed — Salaried Professional, UAE',
        'account_style' => 'personal',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'city' => 'Abu Dhabi',
        'country_hint' => 'United Arab Emirates',
        'salary_range' => [12000, 22000],
        'merchant_tags' => ['groceries', 'fuel', 'utilities', 'streaming', 'restaurants'],
        'transfer_patterns' => ['domestic'],
    ],
    [
        'id' => 'freelancer_germany',
        'label' => 'Maria — Freelancer, Germany',
        'account_style' => 'personal',
        'financial_behaviour' => 'digital_first',
        'volume' => 'medium',
        'city' => 'Munich',
        'country_hint' => 'Germany',
        'salary_range' => [2500, 6000],
        'merchant_tags' => ['saas', 'subscription', 'coffee', 'groceries'],
        'transfer_patterns' => ['domestic', 'occasional_intl'],
    ],
    [
        'id' => 'investor_uk',
        'label' => 'David — Investor, UK',
        'account_style' => 'investor',
        'financial_behaviour' => 'intl_traveller',
        'volume' => 'high',
        'city' => 'London',
        'country_hint' => 'United Kingdom',
        'salary_range' => [8000, 25000],
        'merchant_tags' => ['investment', 'travel', 'hotels', 'premium'],
        'transfer_patterns' => ['international', 'domestic'],
    ],
    [
        'id' => 'personal_conservative_us',
        'label' => 'Emily — Conservative Saver, US',
        'account_style' => 'personal',
        'financial_behaviour' => 'conservative',
        'volume' => 'low',
        'city' => 'Chicago',
        'country_hint' => 'United States',
        'salary_range' => [3500, 5500],
        'merchant_tags' => ['groceries', 'utilities', 'insurance'],
        'transfer_patterns' => ['small_domestic'],
    ],
    [
        'id' => 'luxury_personal_ae',
        'label' => 'Layla — Luxury Lifestyle, UAE',
        'account_style' => 'personal',
        'financial_behaviour' => 'luxury',
        'volume' => 'high',
        'city' => 'Dubai',
        'country_hint' => 'United Arab Emirates',
        'salary_range' => [20000, 50000],
        'merchant_tags' => ['premium', 'travel', 'restaurants', 'retail', 'hotels'],
        'transfer_patterns' => ['domestic', 'international'],
    ],
    [
        'id' => 'student_nigeria',
        'label' => 'Chidi — Student, Lagos',
        'account_style' => 'student',
        'financial_behaviour' => 'cash_heavy',
        'volume' => 'low',
        'city' => 'Lagos',
        'country_hint' => 'Nigeria',
        'salary_range' => [50000, 150000],
        'merchant_tags' => ['tuition', 'transit', 'food', 'streaming'],
        'transfer_patterns' => ['small_domestic'],
    ],
    [
        'id' => 'business_ng',
        'label' => 'Ngozi — Small Business, Nigeria',
        'account_style' => 'business',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'city' => 'Lagos',
        'country_hint' => 'Nigeria',
        'salary_range' => [200000, 800000],
        'merchant_tags' => ['supplier', 'payroll', 'utilities', 'tax'],
        'transfer_patterns' => ['domestic'],
    ],
    [
        'id' => 'dormant_personal',
        'label' => 'Quiet Account — Minimal Activity',
        'account_style' => 'personal',
        'financial_behaviour' => 'conservative',
        'volume' => 'low',
        'city' => '',
        'country_hint' => '',
        'salary_range' => [2000, 4000],
        'merchant_tags' => ['utilities'],
        'transfer_patterns' => [],
    ],
];
