<?php
/**
 * Demo account personas — behaviour templates only; adapt to bank operating country.
 * Do not modify user records. Banks/merchants always follow system operating country.
 */
return [
    [
        'id' => 'student_berlin_24',
        'label' => 'Student — limited income',
        'account_style' => 'student',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'salary_band' => 'entry',
        'merchant_tags' => ['coffee', 'streaming', 'tuition', 'transit', 'groceries'],
    ],
    [
        'id' => 'business_owner_dubai',
        'label' => 'Business owner — payroll & suppliers',
        'account_style' => 'business',
        'financial_behaviour' => 'active_spender',
        'volume' => 'high',
        'salary_band' => 'executive',
        'merchant_tags' => ['saas', 'supplier', 'payroll', 'tax', 'travel'],
    ],
    [
        'id' => 'salaried_uae',
        'label' => 'Salaried professional',
        'account_style' => 'personal',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'salary_band' => 'standard',
        'merchant_tags' => ['groceries', 'fuel', 'utilities', 'streaming', 'restaurants'],
    ],
    [
        'id' => 'freelancer_germany',
        'label' => 'Freelancer / gig economy',
        'account_style' => 'personal',
        'financial_behaviour' => 'digital_first',
        'volume' => 'medium',
        'salary_band' => 'standard',
        'merchant_tags' => ['saas', 'subscription', 'coffee', 'groceries'],
    ],
    [
        'id' => 'investor_uk',
        'label' => 'Investor — travel & dividends',
        'account_style' => 'investor',
        'financial_behaviour' => 'intl_traveller',
        'volume' => 'high',
        'salary_band' => 'executive',
        'merchant_tags' => ['investment', 'travel', 'hotels', 'premium'],
    ],
    [
        'id' => 'personal_conservative_us',
        'label' => 'Conservative saver',
        'account_style' => 'personal',
        'financial_behaviour' => 'conservative',
        'volume' => 'low',
        'salary_band' => 'entry',
        'merchant_tags' => ['groceries', 'utilities', 'insurance'],
    ],
    [
        'id' => 'luxury_personal_ae',
        'label' => 'Luxury / premium lifestyle',
        'account_style' => 'personal',
        'financial_behaviour' => 'luxury',
        'volume' => 'high',
        'salary_band' => 'premium',
        'merchant_tags' => ['premium', 'travel', 'restaurants', 'retail', 'hotels'],
    ],
    [
        'id' => 'student_nigeria',
        'label' => 'Student — cash-heavy',
        'account_style' => 'student',
        'financial_behaviour' => 'cash_heavy',
        'volume' => 'low',
        'salary_band' => 'entry',
        'merchant_tags' => ['tuition', 'transit', 'food', 'streaming'],
    ],
    [
        'id' => 'business_ng',
        'label' => 'Small business',
        'account_style' => 'business',
        'financial_behaviour' => 'average',
        'volume' => 'medium',
        'salary_band' => 'standard',
        'merchant_tags' => ['supplier', 'payroll', 'utilities', 'tax'],
    ],
    [
        'id' => 'dormant_personal',
        'label' => 'Quiet account — minimal activity',
        'account_style' => 'personal',
        'financial_behaviour' => 'conservative',
        'volume' => 'low',
        'salary_band' => 'minimal',
        'merchant_tags' => ['utilities'],
    ],
];
